name: 软件开发 - 持续集成和部署
description: '[持续集成](https://en.wikipedia.org/wiki/Continuous_integration)和[持续部署](https://en.wikipedia.org/wiki/Continuous_deployment)的软件和工具。'
redirect:
  - title: awesome-sysadmin/持续集成和部署
    url: https://github.com/awesome-foss/awesome-sysadmin#continuous-integration--continuous-deployment
related_tags:
  - 自动化
